### ISSUE TITLE
Missing color, icon on namespace

### ISSUE THREAD

**Issue by pelikhan** [sabas1080/pxt-gps#10]
Also prepend all block names with "gps ". As an icon you could use "\uf041"

**Comment by pelikhan** [comment]
You'll find the icon values in the font type via the debugger:
![image](https://user-images.githubusercontent.com/4175913/50751763-071aaf00-1200-11e9-9306-a03dd3160eca.png)

**Comment by sabas1080** [comment]
Wow great
